#!/usr/bin/env python3
# 일회용 번역 스크립트
import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

T = {
  'en': {
    'Studio': {
      'title': '🛠️ Studio',
      'undo': '↶ Undo',
      'redo': '↷ Redo',
      'worldName': 'World Name',
      'addShape': 'Add Shape',
      'shapeCube': 'Cube',
      'shapeSphere': 'Sphere',
      'shapeCylinder': 'Cylinder',
      'shapePlane': 'Plane',
      'myAssets': 'My FBX Assets ({count})',
      'addAsset': '+ Add',
      'closeAssetPicker': 'Close',
      'noAssets': 'No FBX uploaded',
      'uploadAt': 'to upload',
      'transformMode': 'Transform Mode (G/R/S)',
      'modeTranslate': 'Move',
      'modeRotate': 'Rotate',
      'modeScale': 'Scale',
      'selectedKind': 'Selected: {kind}',
      'position': 'Position (m)',
      'rotation': 'Rotation (°)',
      'scale': 'Scale (m)',
      'color': 'Color',
      'delete': '🗑️ Delete (Del)',
      'stats': '{count} objects · History {idx}/{total}',
      'save': '💾 Save',
      'update': '💾 Update',
      'saving': 'Saving…',
      'saved': 'Saved',
      'saveFailed': 'Save failed',
      'playTest': '▶ Test Play',
      'newWorldDefault': 'New World',
      'hudHint': 'L-click: Rotate · R-click: Pan · Wheel: Zoom · Click: Select · Del: Delete · Ctrl+Z/Y: Undo'
    },
    'Worlds': {
      'title': 'Worlds',
      'subtitle': 'Maps I made and public maps from others',
      'newWorld': '+ Create New World',
      'tabMine': '🛠️ My Worlds',
      'tabPublic': '🌐 Public Worlds',
      'loading': 'Loading…',
      'noMineLoggedIn': 'No worlds created yet.',
      'studioHere': 'to start creating',
      'studioLink': 'Studio',
      'loginRequired': 'Login required.',
      'noPublic': 'No public worlds yet.',
      'badgePublic': 'Public',
      'badgePrivate': 'Private',
      'play': '▶ Play',
      'edit': 'Edit',
      'togglePrivate': 'Make Private',
      'togglePublic': 'Make Public',
      'by': 'by',
      'confirmDelete': 'Delete world "{name}"?'
    },
    'World': {
      'loading': 'Loading world…',
      'alpWorld': 'ALP World',
      'playersOnline': '{count} online',
      'youSuffix': '(You)',
      'playersList': '👥 Players',
      'controlHint': 'Click to lock mouse | WASD move | Space jump | Shift sprint | ESC release',
      'chatPlaceholder': 'Type message…',
      'chatEmpty': 'No messages yet'
    },
    'Character': {
      'title': '🎮 Create Character',
      'name': 'Character Name',
      'namePlaceholder': 'Enter name (max 30)',
      'nameRequired': 'Please enter a name.',
      'model3d': '3D Model (Optional)',
      'noModelHint': 'Default block character if no FBX',
      'selectFromAssets': '📂 Select from My Assets',
      'selectOther': 'Choose Another Model',
      'sizeLabel': 'Size (1.0 = 1.8m)',
      'rotationXLabel': 'X Rotation (adjust if lying down)',
      'animMapping': 'Animation Mapping ({count} found)',
      'idleAnimLabel': 'When idle (Idle)',
      'walkAnimLabel': 'When moving (Walk)',
      'noneOption': '— None —',
      'previewIdle': '▶ Preview Idle',
      'previewWalk': '▶ Preview Walk',
      'bodyColor': 'Shirt Color',
      'skinColor': 'Skin Color',
      'hairColor': 'Hair Color',
      'pantsColor': 'Pants Color',
      'enterWorld': 'Enter World 🌍',
      'saving': 'Saving…',
      'networkError': 'Network error',
      'saveFailed': 'Save failed',
      'assetPickerTitle': '📦 Select Asset',
      'loadingAssets': 'Loading…',
      'noUploadedAssets': 'No uploaded assets.',
      'uploadAtAssets': 'to upload an FBX first.'
    },
    'Assets': {
      'title': '3D Asset Library',
      'subtitle': 'Upload FBX files · Max {maxMb}MB',
      'uploadingPercent': 'Uploading… {progress}%',
      'dragHint': 'Click or drag a file here',
      'fileTypeHint': 'FBX only · Max {maxMb}MB',
      'fbxOnly': 'Only FBX files are supported.',
      'sizeOverLimit': 'File exceeds {maxMb}MB',
      'myAssetsCount': 'My Assets ({count})',
      'emptyState': 'No uploaded assets.',
      'emptyHint': 'Drag or click to add a file above.',
      'publishing': 'Public',
      'private': 'Private',
      'download': '↓ Download',
      'delete': 'Delete',
      'confirmDelete': 'Delete this asset?'
    }
  },
  'ja': {
    'Studio': {
      'title': '🛠️ スタジオ',
      'undo': '↶ 元に戻す',
      'redo': '↷ やり直し',
      'worldName': 'ワールド名',
      'addShape': '図形を追加',
      'shapeCube': 'キューブ',
      'shapeSphere': '球',
      'shapeCylinder': '円柱',
      'shapePlane': '平面',
      'myAssets': 'マイFBXアセット ({count})',
      'addAsset': '+ 追加',
      'closeAssetPicker': '閉じる',
      'noAssets': 'アップロードされたFBXなし',
      'uploadAt': 'からアップロード',
      'transformMode': '変形モード (G/R/S)',
      'modeTranslate': '移動',
      'modeRotate': '回転',
      'modeScale': 'サイズ',
      'selectedKind': '選択中: {kind}',
      'position': '位置 (m)',
      'rotation': '回転 (°)',
      'scale': 'サイズ (m)',
      'color': 'カラー',
      'delete': '🗑️ 削除 (Del)',
      'stats': 'オブジェクト {count}個 · 履歴 {idx}/{total}',
      'save': '💾 保存',
      'update': '💾 更新',
      'saving': '保存中…',
      'saved': '保存しました',
      'saveFailed': '保存失敗',
      'playTest': '▶ プレイテスト',
      'newWorldDefault': '新しいワールド',
      'hudHint': '左クリック: 回転 · 右クリック: 移動 · ホイール: 拡大/縮小 · クリック: 選択 · Del: 削除 · Ctrl+Z/Y: 元に戻す'
    },
    'Worlds': {
      'title': 'ワールド',
      'subtitle': '自分が作ったマップと他の人が公開したマップ',
      'newWorld': '+ 新しいワールドを作成',
      'tabMine': '🛠️ 自分が作った',
      'tabPublic': '🌐 公開ワールド',
      'loading': '読み込み中…',
      'noMineLoggedIn': '作成したワールドはありません。',
      'studioHere': 'で作ってみましょう',
      'studioLink': 'スタジオ',
      'loginRequired': 'ログインが必要です。',
      'noPublic': '公開ワールドはまだありません。',
      'badgePublic': '公開',
      'badgePrivate': '非公開',
      'play': '▶ プレイ',
      'edit': '編集',
      'togglePrivate': '非公開にする',
      'togglePublic': '公開する',
      'by': 'by',
      'confirmDelete': 'ワールド「{name}」を削除しますか？'
    },
    'World': {
      'loading': 'ワールド読み込み中…',
      'alpWorld': 'ALP World',
      'playersOnline': '{count}人接続中',
      'youSuffix': '(自分)',
      'playersList': '👥 プレイヤー',
      'controlHint': 'クリックでマウスがロック | WASD移動 | Spaceジャンプ | Shift走る | ESC解除',
      'chatPlaceholder': 'メッセージ入力…',
      'chatEmpty': 'まだチャットがありません'
    },
    'Character': {
      'title': '🎮 キャラクター作成',
      'name': 'キャラクター名',
      'namePlaceholder': '名前を入力 (最大30文字)',
      'nameRequired': '名前を入力してください。',
      'model3d': '3Dモデル (任意)',
      'noModelHint': 'FBXなしの場合ブロックキャラクターで表示',
      'selectFromAssets': '📂 マイアセットから選択',
      'selectOther': '別のモデルを選択',
      'sizeLabel': 'サイズ (1.0 = 1.8m)',
      'rotationXLabel': 'X回転 (横になった時に調整)',
      'animMapping': 'アニメーションマッピング ({count}個検出)',
      'idleAnimLabel': '待機時 (Idle)',
      'walkAnimLabel': '移動時 (Walk)',
      'noneOption': '— なし —',
      'previewIdle': '▶ Idle プレビュー',
      'previewWalk': '▶ Walk プレビュー',
      'bodyColor': '上着の色',
      'skinColor': '肌の色',
      'hairColor': '髪の色',
      'pantsColor': 'ズボンの色',
      'enterWorld': 'ワールドに入る 🌍',
      'saving': '保存中…',
      'networkError': 'ネットワークエラー',
      'saveFailed': '保存失敗',
      'assetPickerTitle': '📦 アセット選択',
      'loadingAssets': '読み込み中…',
      'noUploadedAssets': 'アップロードされたアセットがありません。',
      'uploadAtAssets': 'でFBXを先にアップロードしてください。'
    },
    'Assets': {
      'title': '3Dアセットライブラリ',
      'subtitle': 'FBXファイルアップロード · 最大{maxMb}MB',
      'uploadingPercent': 'アップロード中… {progress}%',
      'dragHint': 'クリックまたはファイルをドラッグ',
      'fileTypeHint': 'FBXのみ · 最大{maxMb}MB',
      'fbxOnly': 'FBXファイルのみサポートします。',
      'sizeOverLimit': 'ファイルサイズ{maxMb}MB超過',
      'myAssetsCount': 'マイアセット ({count})',
      'emptyState': 'アップロードされたアセットがありません。',
      'emptyHint': '上にファイルをドラッグまたはクリックして追加してください。',
      'publishing': '公開中',
      'private': '非公開',
      'download': '↓ ダウンロード',
      'delete': '削除',
      'confirmDelete': '削除しますか？'
    }
  },
  'zh': {
    'Studio': {
      'title': '🛠️ 工作室',
      'undo': '↶ 撤销',
      'redo': '↷ 重做',
      'worldName': '世界名称',
      'addShape': '添加形状',
      'shapeCube': '立方体',
      'shapeSphere': '球体',
      'shapeCylinder': '圆柱',
      'shapePlane': '平面',
      'myAssets': '我的FBX资源 ({count})',
      'addAsset': '+ 添加',
      'closeAssetPicker': '关闭',
      'noAssets': '未上传FBX',
      'uploadAt': '上传',
      'transformMode': '变换模式 (G/R/S)',
      'modeTranslate': '移动',
      'modeRotate': '旋转',
      'modeScale': '缩放',
      'selectedKind': '已选: {kind}',
      'position': '位置 (m)',
      'rotation': '旋转 (°)',
      'scale': '缩放 (m)',
      'color': '颜色',
      'delete': '🗑️ 删除 (Del)',
      'stats': '对象 {count} 个 · 历史 {idx}/{total}',
      'save': '💾 保存',
      'update': '💾 更新',
      'saving': '保存中…',
      'saved': '已保存',
      'saveFailed': '保存失败',
      'playTest': '▶ 试玩',
      'newWorldDefault': '新世界',
      'hudHint': '左键: 旋转 · 右键: 平移 · 滚轮: 缩放 · 单击: 选择 · Del: 删除 · Ctrl+Z/Y: 撤销'
    },
    'Worlds': {
      'title': '世界',
      'subtitle': '我创建的地图和其他人公开的地图',
      'newWorld': '+ 创建新世界',
      'tabMine': '🛠️ 我的世界',
      'tabPublic': '🌐 公开世界',
      'loading': '加载中…',
      'noMineLoggedIn': '尚未创建世界。',
      'studioHere': '开始创建',
      'studioLink': '工作室',
      'loginRequired': '需要登录。',
      'noPublic': '暂无公开世界。',
      'badgePublic': '公开',
      'badgePrivate': '私有',
      'play': '▶ 游玩',
      'edit': '编辑',
      'togglePrivate': '设为私有',
      'togglePublic': '设为公开',
      'by': 'by',
      'confirmDelete': '删除世界「{name}」？'
    },
    'World': {
      'loading': '世界加载中…',
      'alpWorld': 'ALP World',
      'playersOnline': '{count} 在线',
      'youSuffix': '(我)',
      'playersList': '👥 玩家',
      'controlHint': '点击锁定鼠标 | WASD 移动 | Space 跳跃 | Shift 奔跑 | ESC 解除',
      'chatPlaceholder': '输入消息…',
      'chatEmpty': '暂无消息'
    },
    'Character': {
      'title': '🎮 创建角色',
      'name': '角色名称',
      'namePlaceholder': '输入名称 (最多30字)',
      'nameRequired': '请输入名称。',
      'model3d': '3D 模型 (可选)',
      'noModelHint': '无 FBX 时显示方块角色',
      'selectFromAssets': '📂 从我的资源选择',
      'selectOther': '选择其他模型',
      'sizeLabel': '大小 (1.0 = 1.8m)',
      'rotationXLabel': 'X 旋转 (躺下时调整)',
      'animMapping': '动画映射 (发现 {count} 个)',
      'idleAnimLabel': '静止时 (Idle)',
      'walkAnimLabel': '移动时 (Walk)',
      'noneOption': '— 无 —',
      'previewIdle': '▶ Idle 预览',
      'previewWalk': '▶ Walk 预览',
      'bodyColor': '上衣颜色',
      'skinColor': '皮肤颜色',
      'hairColor': '头发颜色',
      'pantsColor': '裤子颜色',
      'enterWorld': '进入世界 🌍',
      'saving': '保存中…',
      'networkError': '网络错误',
      'saveFailed': '保存失败',
      'assetPickerTitle': '📦 选择资源',
      'loadingAssets': '加载中…',
      'noUploadedAssets': '无已上传资源。',
      'uploadAtAssets': '先上传 FBX。'
    },
    'Assets': {
      'title': '3D 资源库',
      'subtitle': '上传 FBX 文件 · 最大 {maxMb}MB',
      'uploadingPercent': '上传中… {progress}%',
      'dragHint': '点击或拖入文件',
      'fileTypeHint': '仅 FBX · 最大 {maxMb}MB',
      'fbxOnly': '仅支持 FBX 文件。',
      'sizeOverLimit': '文件超过 {maxMb}MB',
      'myAssetsCount': '我的资源 ({count})',
      'emptyState': '无已上传资源。',
      'emptyHint': '请在上方拖入或点击添加文件。',
      'publishing': '公开中',
      'private': '私有',
      'download': '↓ 下载',
      'delete': '删除',
      'confirmDelete': '确定删除？'
    }
  }
}

for lang, sections in T.items():
    path = f'messages/{lang}.json'
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    for section, keys in sections.items():
        data[section] = {**data.get(section, {}), **keys}
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'[OK] {path}')
